channels:
  - conda-forge
  - defaults
dependencies:
  # run
  - astropy
  - cfitsio  # for fpack and builds
  - des-desmeds
  - des-pixcorrect
  - des-pizza-cutter-metadetect
  - esutil
  - fitsio
  - galsim
  - importlib_metadata
  - joblib
  - lsstdesc-coord
  - meds
  - ngmix
  - numpy
  - piff
  - pixmappy
  - psfex
  - pyyaml
  - scipy
  - setuptools
  # host setup.py
  - setuptools_scm
  - setuptools_scm_git_archive
  # host build
  - autoconf
  - automake
  - blas-devel=*=*openblas
  - compilers
  - fftw
  - libtool
