channels:
  - conda-forge
  - defaults
dependencies:
  # run
  - astropy
  - lsstdesc-coord
  - des-desmeds
  - esutil
  - fitsio
  - galsim
  - importlib_metadata  
  - joblib
  - meds
  - ngmix
  - numpy
  - piff
  - pixmappy
  - setuptools
  - psfex
  - pyyaml
  - scipy
  # host setup.py
  - setuptools_scm
  - setuptools_scm_git_archive
  # host build
  - autoconf
  - automake
  - blas-devel=*=*openblas
  - cfitsio
  - compilers
  - fftw
