channels:
  - conda-forge
  - defaults
dependencies:
  - astropy
  - autoconf
  - automake
  - blas-devel=*=*openblas
  - cfitsio
  - compilers
  - cython
  - des-desmeds
  - des-pizza-cutter
  - esutil
  - fitsio
  - fftw
  - galsim
  - h5py
  - joblib
  - libtool
  - mamba
  - matplotlib
  - meds
  - metadetect
  - ngmix=1.3
  - numpy
  - numba
  - piff
  - psfex
  - pixmappy
  - pip
  - pyyaml
  - python=3.8
  - pybind11
  - scipy
  - tqdm
  - setuptools_scm
  - setuptools_scm_git_archive
  - importlib_metadata
