channels:
  - conda-forge
  - defaults
dependencies:
  - autoconf
  - automake
  - libtool
  - python=3.8
  - numpy
  - astropy
  - pip
  - pyyaml
  - numba
  - scipy
  - cython
  - matplotlib
  - pybind11
  - fitsio
  - fftw
  - galsim
  - tqdm
  - h5py
  - cfitsio
  - ngmix=1.3
  - meds
  - metadetect
  - piff
  - esutil
  - des-desmeds
  - des-pizza-cutter
  - psfex
  - pixmappy
  - joblib
  - compilers
  - mamba
  - libblas=*=*openblas
