codecov:
  branch: main

fixes:
  # Fix the file names
  - "/home/runner/work/Piff/Piff/::"
  - "/opt/hostedtoolcache/Python/*/x64/lib/python*/site-packages/::"
  - "/Users/runner/hostedtoolcache/Python/*/x64/lib/python*/site-packages/::"


coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        enabled: yes
        target: 100%
        threshold: 1%
        branches: null

    patch:
      default:
        target: auto
        threshold: 1%
        branches: null

    changes: false

  ignore: null

comment: false
