name: tests

on:
  push:
    branches:
      - main
  pull_request: null

jobs:
  tests:
    name: tests
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v2

      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.11
          channels: conda-forge,defaults
          channel-priority: strict
          show-channel-urls: true
          miniforge-version: latest
          miniforge-variant: Mambaforge
          environment-file: environment.yaml

      - name: configure conda and install code
        shell: bash -l {0}
        run: |
          mamba install pytest flake8
          python -m pip install -e . -vv

      - name: run cli
        shell: bash -l {0}
        run: |
          eastlake-swarp -dd
          eastlake-src-extractor -dd
          run-eastlake-sim --help

      - name: test
        shell: bash -l {0}
        run: |
          git clone https://github.com/beckermr/des-test-data
          export TEST_DESDATA=`pwd`/des-test-data
          pytest -vvs eastlake

      - name: lint
        shell: bash -l {0}
        run: |
          flake8 eastlake
